module.exports = {
  darkMode: 'class',
  content: [
    // Or if using `src` directory:
    './src/**/*.{js,ts,jsx,tsx}',
    './src/**/**/*.{js,ts,jsx,tsx}',
    './src/**/**/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        // Add your custom colors here
        customRed: '#FF0000',
        customBlue: '#0000FF',
        primary2: 'var(--color-primary)',
        primary: 'rgb(var(--color-primary))',
        secondary: 'rgb(var(--color-secondary))',
        backgroundone: 'rgb(var(--color-background-one))',
        backgroundtwo: 'rgb(var(--color-background-two))',
        backgroundthree: 'rgb(var(--color-background-three))',
        backgroundfour: 'rgb(var(--color-background-four))',
        texttest: '#d2bab0',
        textone: 'var(--color-text-one)',
        texttwo: 'var(--color-text-two)',
        backgroundonedark: 'var(--color-background-one-dark)',
        backgroundtwodark: 'var(--color-background-two-dark)',
        backgroundthreedark: 'var(--color-background-three-dark)',
        backgroundfourdark: 'var(--color-background-four-dark)',
        textonedark: 'var(--color-text-one-dark)',
        texttwodark: 'var(--color-text-two-dark)',
        accent: 'rgb(var(--color-accent))',
        bg1: 'var(--color-background-one)',
        bg1p5: 'var(--color-background-one5)',
        bg2: 'var(--color-background-two)',
        bg3: 'var(--color-background-three)',
        bg4: 'var(--color-background-four)',
        bg5: 'var(--color-background-five)',
        bg6: 'var(--color-background-six)',
        bg0dark: 'var(--color-background-zero-dark)',
        bg1dark: 'var(--color-background-one-dark)',
        bg2dark: 'var(--color-background-two-dark)',
        bg3dark: 'var(--color-background-three-dark)',
        bg4dark: 'var(--color-background-four-dark)',
        bg5dark: 'var(--color-background-five-dark)',
        bg6dark: 'var(--color-background-six-dark)',
        prim1: 'var(--color-prim-100)',
        prim2: 'var(--color-prim-200)',
        prim3: 'var(--color-prim-300)',
        prim4: 'var(--color-prim-400)',
        prim5: 'var(--color-prim-500)',
        prim6: 'var(--color-prim-600)',
        topbar: 2 == 1 ? 'var(--color-background-two)' : 'var(--color-background-five1)',
        topbarshadow: 2 == 1 ? 'var(--color-background-five)' : 'var(--color-background-four1)',
        menu: 2 == 1 ? 'var(--color-background-two)' : 'var(--color-background-four1)',
        navigation: 2 == 1 ? 'var(--color-background-two)' : 'var(--color-background-two1)',
        breadcrumb: 2 == 1 ? 'var(--color-background-two)' : 'var(--color-background-two1)',
        toolbar: 2 == 1 ? 'var(--color-background-two)' : 'var(--color-background-two1)',
        table: 2 == 1 ? 'var(--color-background-one)' : 'var(--color-background-one1)',
        tableHead: 2 == 1 ? 'var(--color-background-two)' : 'var(--color-background-two1)',
        hoverItem: 2 == 1 ? 'var(--color-background-three)' : 'var(--color-background-four1)',
        selectedItem: 2 == 1 ? 'var(--color-background-four)' : 'var(--color-background-five1)',
        hairlineStructure: 2 == 1 ? 'var(--color-background-four)' : 'var(--color-background-one)',
        // ...
      },
    },
  },
  variants: {
    backgroundColor: ({ after }) => after(['disabled']),
    textColor: ({ after }) => after(['disabled']),
    extend: {
      width: ['focus'],
    },
  },
  plugins: [],
}
